### ISSUE TITLE
mimics can spawn without replacing the chests in desert pyramids, and apparently simple dungeons too

### ISSUE THREAD

**Issue by Nathan22211** [LukeGrahamLandry/mimic-mod#4]
[lexi0tschka](https://www.curseforge.com/members/lexi0tschka) mentioned the simple dungeons. Instead of 4 chests in the pyramid, there were 6 counting the legged ones
![2022-08-05_16 34 14](https://user-images.githubusercontent.com/35241068/183211675-83c35ffa-fe46-4df7-a682-939c0badd769.png)

**Comment by CyberSteve777** [comment]
It happens in other dungeons too, like, end cities
